### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by stigespen** [ThomasKur/IntuneDocumentation#2] opened 2018-06-28 08:13 UTC
Getting this when attempting to run: 

At C:\users\stigespen\Desktop\DocumentIntune.ps1:901 char:20
+     if($resultÂ -eqÂ "OK")Â Â Â Â {Â Â Â Â
+                    ~
You must provide a value expression following the '-eq' operator.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:901 char:20
+     if($resultÂ -eqÂ "OK")Â Â Â Â {Â Â Â Â
+                    ~
Unexpected token 'Â' in expression or statement.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:901 char:20
+     if($resultÂ -eqÂ "OK")Â Â Â Â {Â Â Â Â
+                    ~
Missing closing ')' after expression in 'if' statement.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:893 char:4
+ try{
+    ~
Missing closing '}' in statement block or type definition.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:901 char:26
+     if($resultÂ -eqÂ "OK")Â Â Â Â {Â Â Â Â
+                          ~
The Try statement is missing its Catch or Finally block.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:901 char:26
+     if($resultÂ -eqÂ "OK")Â Â Â Â {Â Â Â Â
+                          ~
Unexpected token ')' in expression or statement.
At C:\users\stigespen\Desktop\DocumentIntune.ps1:910 char:1
+ } catch {
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedValueExpression

**Comment by ThomasKur** [comment] 2018-06-29 07:58
Have you tried with the new version? published two days ago? Because there where some character set mismatches and I corrected them. At the moment I cannot reproduce it.

**Comment by stigespen** [comment] 2018-06-29 10:33
Tried again now with the same result. Downloaded the script directly from GitHub with wget.

Opened the script in Notepad++, converted it to ANSI encoding - and now it works fine. (The encoding was UTF-8)

**Comment by ThomasKur** [comment] 2018-07-01 15:00
So I did now the same and uploaded it again. I hope it is now fixed. When I download it again, it works on my machines.

**Closed as completed** 2018-07-04 14:56 UTC
